Repository edu-pi/Front, pull requests merged in 2024-11, with the labels that each got.

#197 [#195]feat: 조작버튼 정리
  public/vite.svg
  src/App.tsx
  src/index.css
  src/mocks/samples/testResponseBody.ts
  src/pages/Home/Home.tsx
  src/pages/Visualization/Visualization.tsx
  src/pages/Visualization/VisualizationClassroom.tsx
  src/pages/Visualization/components/LeftSection/LeftSection.module.css
  src/pages/Visualization/components/LeftSection/LeftSection.tsx
  src/pages/Visualization/components/LeftSection/components/Dropdown.tsx
  src/pages/Visualization/components/RightSection/RightSection.module.css
  src/pages/Visualization/components/RightSection/RightSection.tsx
  src/pages/components/LoggedInClassroomHeader.tsx
  src/pages/components/LoggedInHeader.tsx
  src/pages/components/PublicHeader.tsx
Labels: front, feat

#298 [#293]fix: 시각화 헤더 삭제 및 메인 link 수정
  src/pages/Home/Home.tsx
  src/pages/components/Header.tsx
Labels: fix, FE

#297 [#284]feat: 입출력 커리큘럼 코드 추가 및 커리큘럼 선택시 시각화, 콘솔 초기화
  src/App.css
  src/pages/Visualization/Visualization.tsx
  src/pages/Visualization/VisualizationClassroom.tsx
  src/pages/Visualization/components/LeftSection/components/Dropdown.tsx
  src/pages/Visualization/components/LeftSection/components/exampleCode.ts
Labels: feat, FE

#292 [#287]feat: 모든 alert 커스텀 alert로 변경
  src/pages/Classroom/Classroom.tsx
  src/pages/ClassroomDashboard/ClassroomDashboard.tsx
  src/pages/Login/Login.tsx
  src/pages/Manage/Manage.tsx
  src/pages/Manage/components/Guest.tsx
  src/pages/Signup/components/SignupWrap.tsx
  src/pages/Visualization/components/RightSection/RightSection.tsx
Labels: feat, FE
